version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=whereby-giggle-latakia-rampant-blacking
  matomo:
    image: matomo
    restart: always
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=root
      - MATOMO_DATABASE_PASSWORD=whereby-giggle-latakia-rampant-blacking
    volumes:
      - ./config:/var/www/html/config
      - matomo:/var/www/html
    ports:
      - 8080:80
volumes:
  matomo:
